### ISSUE TITLE
Enable gzip

### ISSUE THREAD

**Issue by eligundry** [grubersjoe/github-contributions-api#3]
Hi, I love react-github-calendar and use it on my static site. I'm trying to get that Lighthouse score to 100 and one of the blockers is that this API isn't gzip'ing it's response. Would it be possible to enable gzip for this? I'm seeing that I could save ~180kb per request.

**Comment by grubersjoe** [comment]
Hey, good point. GZIP should be enabled of course 👍🏽. I've added support for it now.

**Comment by eligundry** [comment]
Thanks!
