### ISSUE TITLE
All contribution counts are 0

### ISSUE THREAD

**Issue by ABaulderstone** [grubersjoe/github-contributions-api#5]
For the last couple days all requests to the API have been returning the correct level, but count for every date in the contributions array is 0 

![Screenshot 2023-11-17 at 1 01 09 pm](https://github.com/grubersjoe/github-contributions-api/assets/46916203/9d727eb3-7dbc-4a5d-8849-6d9a75c57b17)

**Comment by grubersjoe** [comment]
I have a fix, but I need to deploy the new version later. Unfortunately, GitHub made scraping the count a lot harder. It's only in their tooltips now.

**Comment by grubersjoe** [comment]
Fixed now
