### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by yangavin** [grubersjoe/github-contributions-api#7]
A regular request to get user's contributions stopped working, getting a response of:

{
"error": "User \\"grubersjoe\\" not found."
}

**Comment by grubersjoe** [comment]
Hey. Thanks for reporting this! GitHub seems to have changed how the contribution graph is rendered. Now client-side JavaScript appears to be required. You can test this by disabling JavaScript in your browser (the chart never shows up, but you will only see a spinner forever). Consequently, the contribution data can no longer be scraped by simply parsing the HTML source.

So this will make this a lot harder, unfortunately, and I have to think about this. There probably is no way around something like Puppeteer which sounds quite heavy.

**Comment by grubersjoe** [comment]
I think I've found a way around Puppeteer so that DOM parsing can still be used.

**Comment by adriangalilea** [comment]
Hey @grubersjoe, why not just use graphql?
<img width="773" alt="image" src="https://github.com/grubersjoe/github-contributions-api/assets/90320947/ebfe7f7d-6255-4b91-a96d-a1827adf6e0a">

[source](https://medium.com/@yuichkun/how-to-retrieve-contribution-graph-data-from-the-github-api-dc3a151b4af)

**Comment by grubersjoe** [comment]
Oh wow, there's an API now? I'm pretty sure there wasn't when I started the project.

In this case of course this is way to go. I'll look into it later. Thanks for the hint!

**Comment by adriangalilea** [comment]
> Oh wow, there's an API now? I'm pretty sure there wasn't when I started the project.

I could not find the documentation anywhere, just that post.

You can take a look at my [crude implementation here](https://github.com/adriangalilea/e-id/blob/main/components/social_component/fetch_github_activity.tsx)

Glad that I helped ;)

**Comment by yangavin** [comment]
Hey @grubersjoe,

It's really unfortunate that GitHub changed their rendering strategy. I was actually using GitHub's GraphQL API and I had two major issues with it that ultimately lead me to using your API:

1. Rate limits
GitHub's API has a rate limit that I found to be too low for fetching large amounts of data, such as contributions:
https://docs.github.com/en/graphql/overview/rate-limits-and-node-limits-for-the-graphql-api
I could be querying it wrong, but I ran into the limit for personal use, I can imagine this may be an issue for a public-facing API.

2. Only showing previous year
Currently there does not seem to be a way to fetch all total contributions, you can only fetch total contributions for the past year (similar to what's shown on your GitHub profile on initial load. There isn't even an option to fetch total contributions within a date range. More about this here:
https://github.com/anuraghazra/github-readme-stats/issues/2269

I resorted to using your API because your web-scraping strategy bypasses these two issues. These are just some things to consider as your working on a fix if you're using GraphQL. While something like Puppeteer may be heavy, it could perhaps bring in a tremendous amount of value that is not currently being supported by GraphQL.

Hope this helps!

**Comment by d3or** [comment]
Hi. PR here that should fix this: https://github.com/grubersjoe/github-contributions-api/pull/8

**Comment by grubersjoe** [comment]
Deployed latest version, everything should work again. Thanks everyone <3!

**Comment by grubersjoe** [comment]
@yangavin I think you made two very good points 👍. The rate limit would probably be reached pretty fast. Scraping is fragile but it solves these two issues.
